export const SET_LOADER = "SET_LOADER";
export const SET_SEARCH_WORD = "SET_SEARCH_WORD";
export const NEW_SEARCH_ADDED = "NEW_SEARCH_ADDED";
export const SELECTED_TIMEZONES_CHANGED = "SELECTED_TIMEZONES_CHANGED";
